# Generated by Django 5.2.4 on 2026-04-17 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('waiting_payment', 'รอชำระเงิน'), ('verifying', 'รอตรวจสอบยอดเงิน'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_image', models.ImageField(upload_to='slips/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='a_maintenance.maintenancerequest')),
            ],
        ),
    ]
