# Generated by Django 5.2.4 on 2026-04-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_maintenance', '0002_maintenancerequest_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_issues/'),
        ),
    ]
