# Generated by Django 5.2.11 on 2026-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'ชื่อผู้ใช้นี้มีคนใช้แล้ว'}, max_length=150, unique=True),
        ),
    ]
