# Generated by Django 5.2.4 on 2026-03-29 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('priority', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง')], default='medium', max_length=20, verbose_name='ลำดับความสำคัญ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนด')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='มอบหมายให้')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': 'งานซ่อมบำรุง',
                'verbose_name_plural': 'งานซ่อมบำรุง',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อรายงาน')),
                ('file', models.FileField(upload_to='monthly_reports/', verbose_name='ไฟล์รายงาน')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่อัปโหลด')),
                ('month', models.IntegerField(verbose_name='เดือน')),
                ('year', models.IntegerField(verbose_name='ปี')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='อัปโหลดโดย')),
            ],
            options={
                'verbose_name': 'รายงานประจำเดือน',
                'verbose_name_plural': 'รายงานประจำเดือน',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
