# Generated by Django 5.2.4 on 2026-05-06 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20, verbose_name='หน่วย/ห้อง')),
                ('tenant_name', models.CharField(max_length=100, verbose_name='ชื่อลูกบ้าน')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('due_date', models.DateField(verbose_name='วันครบกำหนด')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='วันชำระ')),
                ('status', models.CharField(choices=[('pending', 'รอชำระ'), ('paid', 'ชำระแล้ว'), ('overdue', 'เกินกำหนด')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='billing_proofs/', verbose_name='หลักฐานการชำระ (สลิป)')),
                ('proof_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ส่งหลักฐาน')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proof_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proofs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่งหลักฐาน')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to=settings.AUTH_USER_MODEL, verbose_name='บัญชีผู้ใช้งาน')),
            ],
            options={
                'verbose_name': 'ใบแจ้งหนี้',
                'verbose_name_plural': 'ใบแจ้งหนี้',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อการแจ้ง')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance_images/', verbose_name='รูปภาพประกอบ')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('priority', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง')], default='medium', max_length=20, verbose_name='ลำดับความสำคัญ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่แจ้ง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดเสร็จ')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='ช่างที่รับผิดชอบ')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แจ้ง (ลูกบ้าน)')),
            ],
            options={
                'verbose_name': 'การแจ้งซ่อม',
                'verbose_name_plural': 'การแจ้งซ่อม',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อรายงาน')),
                ('file', models.FileField(upload_to='monthly_reports/', verbose_name='ไฟล์รายงาน')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่อัปโหลด')),
                ('month', models.IntegerField(verbose_name='เดือน (1-12)')),
                ('year', models.IntegerField(verbose_name='ปี (ค.ศ.)')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='อัปโหลดโดย')),
            ],
            options={
                'verbose_name': 'รายงานประจำเดือน',
                'verbose_name_plural': 'รายงานประจำเดือน',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
