# Generated by Django 5.2.4 on 2026-03-29 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20, verbose_name='ห้อง')),
                ('tenant_name', models.CharField(max_length=100, verbose_name='ชื่อผู้เช่า')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('due_date', models.DateField(verbose_name='วันครบกำหนด')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='วันชำระ')),
                ('status', models.CharField(choices=[('pending', 'ค้างชำระ'), ('paid', 'ชำระแล้ว'), ('overdue', 'เลยกำหนด')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'ใบแจ้งหนี้',
                'verbose_name_plural': 'ใบแจ้งหนี้',
                'ordering': ['-due_date'],
            },
        ),
    ]
