# Generated by Django 5.2.4 on 2026-04-17 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('Pending', 'รอดำเนินการ'), ('In Progress', 'กำลังซ่อม'), ('Done', 'เสร็จสิ้น')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20, verbose_name='หน่วย')),
                ('tenant_name', models.CharField(max_length=100, verbose_name='ชื่อผู้เช่า/ลูกบ้าน')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('due_date', models.DateField(verbose_name='วันครบกำหนด')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='วันชำระ')),
                ('status', models.CharField(choices=[('pending', 'รอชำระ'), ('paid', 'ชำระแล้ว'), ('overdue', 'เกินกำหนด')], default='pending', max_length=20)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='billing_proofs/', verbose_name='หลักฐานการชำระ')),
                ('proof_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proof_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='monthly_reports/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
