# Generated by Django 5.2.4 on 2026-04-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_billinginvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='billing_proofs/', verbose_name='หลักฐานการชำระ'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ส่งหลักฐาน'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='proof_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่งหลักฐาน'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เช่า'),
        ),
    ]
