# Generated by Django 5.2.4 on 2026-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('JURISTIC', 'นิติบุคคล'), ('SECURITY', 'รปภ.'), ('RESIDENT', 'ลูกบ้าน')], default='RESIDENT', max_length=20),
        ),
    ]
