# Generated by Django 5.2.4 on 2026-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('resident', 'ลูกบ้าน'), ('juristic', 'นิติบุคคล'), ('security', 'รปภ.')], default='resident', max_length=20),
        ),
    ]
