MOCK_CAMERAS = [
    {
        'name': 'CAM-01',
        'location': 'Main Entrance',
        'status': 'active',
        'stream_url': '',
        'image_url': 'images/main-entrance.png',
        'is_demo': True,
    },
    {
        'name': 'CAM-02',
        'location': 'Lobby',
        'status': 'active',
        'stream_url': '',
        'image_url': 'images/lobby.png',
        'is_demo': True,
    },
    {
        'name': 'CAM-03',
        'location': 'Parking B1',
        'status': 'active',
        'stream_url': '',
        'image_url': 'images/parking-b1.png',
        'is_demo': True,
    },
    {
        'name': 'CAM-04',
        'location': 'Elevator Hall',
        'status': 'maintenance',
        'stream_url': '',
        'image_url': 'images/elevator-hall.png',
        'is_demo': True,
    },
    {
        'name': 'CAM-05',
        'location': 'Mail Room',
        'status': 'active',
        'stream_url': '',
        'image_url': 'images/mail-room.png',
        'is_demo': True,
    },
    {
        'name': 'CAM-06',
        'location': 'Swimming Pool',
        'status': 'active',
        'stream_url': '',
        'image_url': 'images/swimming-pool.png',
        'is_demo': True,
    },
    {
        'name': 'CAM-07',
        'location': 'Fitness Center',
        'status': 'inactive',
        'stream_url': '',
        'image_url': '',
        'is_demo': True,
    },
    {
        'name': 'CAM-08',
        'location': 'Loading Bay',
        'status': 'inactive',
        'stream_url': '',
        'image_url': '',
        'is_demo': True,
    },
    {
        'name': 'CAM-09',
        'location': 'Rooftop Access',
        'status': 'inactive',
        'stream_url': '',
        'image_url': '',
        'is_demo': True,
    },
    {
        'name': 'CAM-10',
        'location': 'Side Gate',
        'status': 'inactive',
        'stream_url': '',
        'image_url': '',
        'is_demo': True,
    },
]
